# Generated by Django 3.2.9 on 2021-11-18 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.IntegerField(unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('physichologist', models.CharField(max_length=150)),
                ('attendance', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('satisfaction', models.IntegerField(null=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook_app.logbook')),
            ],
        ),
    ]
